export const style = {
  'Radio': {
    'meta': {
      'variants': {
        'status': [
          'error',
        ],
        'size': [
          'small',
          'big',
        ],
      },
      'states': [
        'checked',
        'disabled',
        'active',
      ],
    },
    'default': {
      'size': 36,
      'innerSize': 24,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderColor': 'gray-primary',
      'selectColor': 'transparent',
      'highlightColor': 'transparent',
    },
    'default.checked': {
      'size': 36,
      'innerSize': 24,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderColor': 'blue-primary',
      'selectColor': 'blue-primary',
      'highlightColor': 'transparent',
    },
    'default.checked.disabled': {
      'size': 36,
      'innerSize': 24,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderColor': 'gray-light',
      'selectColor': 'gray-primary',
      'highlightColor': 'transparent',
    },
    'default.checked.active': {
      'size': 36,
      'innerSize': 24,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderColor': 'blue-dark',
      'selectColor': 'blue-primary',
      'highlightColor': 'gray-light',
    },
    'default.checked.disabled.active': {
      'size': 36,
      'innerSize': 24,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderColor': 'blue-dark',
      'selectColor': 'gray-primary',
      'highlightColor': 'gray-light',
    },
    'default.disabled': {
      'size': 36,
      'innerSize': 24,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderColor': 'gray-light',
      'selectColor': 'transparent',
      'highlightColor': 'transparent',
    },
    'default.disabled.active': {
      'size': 36,
      'innerSize': 24,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderColor': 'gray-dark',
      'selectColor': 'transparent',
      'highlightColor': 'gray-light',
    },
    'default.active': {
      'size': 36,
      'innerSize': 24,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderColor': 'gray-dark',
      'selectColor': 'transparent',
      'highlightColor': 'gray-light',
    },
    'default.error': {
      'size': 36,
      'innerSize': 24,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderColor': 'pink-primary',
      'selectColor': 'transparent',
      'highlightColor': 'transparent',
    },
    'default.error.small': {
      'size': 30,
      'innerSize': 20,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderColor': 'pink-primary',
      'selectColor': 'transparent',
      'highlightColor': 'transparent',
    },
    'default.error.big': {
      'size': 42,
      'innerSize': 28,
      'highlightSize': 70,
      'borderWidth': 2,
      'borderColor': 'pink-primary',
      'selectColor': 'transparent',
      'highlightColor': 'transparent',
    },
    'default.small': {
      'size': 30,
      'innerSize': 20,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderColor': 'gray-primary',
      'selectColor': 'transparent',
      'highlightColor': 'transparent',
    },
    'default.big': {
      'size': 42,
      'innerSize': 28,
      'highlightSize': 70,
      'borderWidth': 2,
      'borderColor': 'gray-primary',
      'selectColor': 'transparent',
      'highlightColor': 'transparent',
    },
    'default.error.checked': {
      'size': 36,
      'innerSize': 24,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderColor': 'pink-primary',
      'selectColor': 'pink-primary',
      'highlightColor': 'transparent',
    },
    'default.error.checked.disabled': {
      'size': 36,
      'innerSize': 24,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderColor': 'gray-light',
      'selectColor': 'gray-primary',
      'highlightColor': 'transparent',
    },
    'default.error.checked.active': {
      'size': 36,
      'innerSize': 24,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderColor': 'pink-primary',
      'selectColor': 'pink-primary',
      'highlightColor': 'gray-light',
    },
    'default.error.checked.disabled.active': {
      'size': 36,
      'innerSize': 24,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderColor': 'pink-primary',
      'selectColor': 'gray-primary',
      'highlightColor': 'gray-light',
    },
    'default.error.disabled': {
      'size': 36,
      'innerSize': 24,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderColor': 'gray-light',
      'selectColor': 'transparent',
      'highlightColor': 'transparent',
    },
    'default.error.disabled.active': {
      'size': 36,
      'innerSize': 24,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderColor': 'gray-dark',
      'selectColor': 'transparent',
      'highlightColor': 'gray-light',
    },
    'default.error.active': {
      'size': 36,
      'innerSize': 24,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderColor': 'gray-dark',
      'selectColor': 'transparent',
      'highlightColor': 'gray-light',
    },
    'default.error.small.checked': {
      'size': 30,
      'innerSize': 20,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderColor': 'pink-primary',
      'selectColor': 'pink-primary',
      'highlightColor': 'transparent',
    },
    'default.error.small.checked.disabled': {
      'size': 30,
      'innerSize': 20,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderColor': 'gray-light',
      'selectColor': 'gray-primary',
      'highlightColor': 'transparent',
    },
    'default.error.small.checked.active': {
      'size': 30,
      'innerSize': 20,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderColor': 'pink-primary',
      'selectColor': 'pink-primary',
      'highlightColor': 'gray-light',
    },
    'default.error.small.checked.disabled.active': {
      'size': 30,
      'innerSize': 20,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderColor': 'pink-primary',
      'selectColor': 'gray-primary',
      'highlightColor': 'gray-light',
    },
    'default.error.small.disabled': {
      'size': 30,
      'innerSize': 20,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderColor': 'gray-light',
      'selectColor': 'transparent',
      'highlightColor': 'transparent',
    },
    'default.error.small.disabled.active': {
      'size': 30,
      'innerSize': 20,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderColor': 'gray-dark',
      'selectColor': 'transparent',
      'highlightColor': 'gray-light',
    },
    'default.error.small.active': {
      'size': 30,
      'innerSize': 20,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderColor': 'gray-dark',
      'selectColor': 'transparent',
      'highlightColor': 'gray-light',
    },
    'default.error.big.checked': {
      'size': 42,
      'innerSize': 28,
      'highlightSize': 70,
      'borderWidth': 2,
      'borderColor': 'pink-primary',
      'selectColor': 'pink-primary',
      'highlightColor': 'transparent',
    },
    'default.error.big.checked.disabled': {
      'size': 42,
      'innerSize': 28,
      'highlightSize': 70,
      'borderWidth': 2,
      'borderColor': 'gray-light',
      'selectColor': 'gray-primary',
      'highlightColor': 'transparent',
    },
    'default.error.big.checked.active': {
      'size': 42,
      'innerSize': 28,
      'highlightSize': 70,
      'borderWidth': 2,
      'borderColor': 'pink-primary',
      'selectColor': 'pink-primary',
      'highlightColor': 'gray-light',
    },
    'default.error.big.checked.disabled.active': {
      'size': 42,
      'innerSize': 28,
      'highlightSize': 70,
      'borderWidth': 2,
      'borderColor': 'pink-primary',
      'selectColor': 'gray-primary',
      'highlightColor': 'gray-light',
    },
    'default.error.big.disabled': {
      'size': 42,
      'innerSize': 28,
      'highlightSize': 70,
      'borderWidth': 2,
      'borderColor': 'gray-light',
      'selectColor': 'transparent',
      'highlightColor': 'transparent',
    },
    'default.error.big.disabled.active': {
      'size': 42,
      'innerSize': 28,
      'highlightSize': 70,
      'borderWidth': 2,
      'borderColor': 'gray-dark',
      'selectColor': 'transparent',
      'highlightColor': 'gray-light',
    },
    'default.error.big.active': {
      'size': 42,
      'innerSize': 28,
      'highlightSize': 70,
      'borderWidth': 2,
      'borderColor': 'gray-dark',
      'selectColor': 'transparent',
      'highlightColor': 'gray-light',
    },
    'default.small.checked': {
      'size': 30,
      'innerSize': 20,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderColor': 'blue-primary',
      'selectColor': 'blue-primary',
      'highlightColor': 'transparent',
    },
    'default.small.checked.disabled': {
      'size': 30,
      'innerSize': 20,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderColor': 'gray-light',
      'selectColor': 'gray-primary',
      'highlightColor': 'transparent',
    },
    'default.small.checked.active': {
      'size': 30,
      'innerSize': 20,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderColor': 'blue-dark',
      'selectColor': 'blue-primary',
      'highlightColor': 'gray-light',
    },
    'default.small.checked.disabled.active': {
      'size': 30,
      'innerSize': 20,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderColor': 'blue-dark',
      'selectColor': 'gray-primary',
      'highlightColor': 'gray-light',
    },
    'default.small.disabled': {
      'size': 30,
      'innerSize': 20,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderColor': 'gray-light',
      'selectColor': 'transparent',
      'highlightColor': 'transparent',
    },
    'default.small.disabled.active': {
      'size': 30,
      'innerSize': 20,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderColor': 'gray-dark',
      'selectColor': 'transparent',
      'highlightColor': 'gray-light',
    },
    'default.small.active': {
      'size': 30,
      'innerSize': 20,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderColor': 'gray-dark',
      'selectColor': 'transparent',
      'highlightColor': 'gray-light',
    },
    'default.big.checked': {
      'size': 42,
      'innerSize': 28,
      'highlightSize': 70,
      'borderWidth': 2,
      'borderColor': 'blue-primary',
      'selectColor': 'blue-primary',
      'highlightColor': 'transparent',
    },
    'default.big.checked.disabled': {
      'size': 42,
      'innerSize': 28,
      'highlightSize': 70,
      'borderWidth': 2,
      'borderColor': 'gray-light',
      'selectColor': 'gray-primary',
      'highlightColor': 'transparent',
    },
    'default.big.checked.active': {
      'size': 42,
      'innerSize': 28,
      'highlightSize': 70,
      'borderWidth': 2,
      'borderColor': 'blue-dark',
      'selectColor': 'blue-primary',
      'highlightColor': 'gray-light',
    },
    'default.big.checked.disabled.active': {
      'size': 42,
      'innerSize': 28,
      'highlightSize': 70,
      'borderWidth': 2,
      'borderColor': 'blue-dark',
      'selectColor': 'gray-primary',
      'highlightColor': 'gray-light',
    },
    'default.big.disabled': {
      'size': 42,
      'innerSize': 28,
      'highlightSize': 70,
      'borderWidth': 2,
      'borderColor': 'gray-light',
      'selectColor': 'transparent',
      'highlightColor': 'transparent',
    },
    'default.big.disabled.active': {
      'size': 42,
      'innerSize': 28,
      'highlightSize': 70,
      'borderWidth': 2,
      'borderColor': 'gray-dark',
      'selectColor': 'transparent',
      'highlightColor': 'gray-light',
    },
    'default.big.active': {
      'size': 42,
      'innerSize': 28,
      'highlightSize': 70,
      'borderWidth': 2,
      'borderColor': 'gray-dark',
      'selectColor': 'transparent',
      'highlightColor': 'gray-light',
    },
  },
  'RadioGroup': {
    'meta': {
      'variants': {},
      'states': [],
    },
    'default': {
      'padding': 0,
    },
  },
  'CheckBox': {
    'meta': {
      'variants': {
        'status': [
          'error',
        ],
        'size': [
          'small',
          'big',
        ],
      },
      'states': [
        'checked',
        'disabled',
        'active',
      ],
    },
    'default': {
      'size': 30,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'gray-primary',
      'backgroundColor': 'gray-light',
      'selectColor': 'transparent',
      'highlightColor': 'transparent',
    },
    'default.checked': {
      'size': 30,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'transparent',
      'backgroundColor': 'blue-primary',
      'selectColor': '#FFFFFF',
      'highlightColor': 'transparent',
    },
    'default.checked.disabled': {
      'size': 30,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'transparent',
      'backgroundColor': 'gray-primary',
      'selectColor': '#FFFFFF',
      'highlightColor': 'transparent',
    },
    'default.checked.active': {
      'size': 30,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'blue-dark',
      'backgroundColor': 'blue-primary',
      'selectColor': '#FFFFFF',
      'highlightColor': 'gray-light',
    },
    'default.checked.disabled.active': {
      'size': 30,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'blue-dark',
      'backgroundColor': 'gray-primary',
      'selectColor': '#FFFFFF',
      'highlightColor': 'gray-light',
    },
    'default.disabled': {
      'size': 30,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'gray-light',
      'backgroundColor': '#F1F5F5',
      'selectColor': 'transparent',
      'highlightColor': 'transparent',
    },
    'default.disabled.active': {
      'size': 30,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'gray-dark',
      'backgroundColor': '#F1F5F5',
      'selectColor': 'transparent',
      'highlightColor': 'gray-light',
    },
    'default.active': {
      'size': 30,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'gray-dark',
      'backgroundColor': 'gray-light',
      'selectColor': 'transparent',
      'highlightColor': 'gray-light',
    },
    'default.error': {
      'size': 30,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'pink-primary',
      'backgroundColor': '#FFC9D9',
      'selectColor': 'transparent',
      'highlightColor': 'transparent',
    },
    'default.error.small': {
      'size': 24,
      'highlightSize': 40,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'pink-primary',
      'backgroundColor': '#FFC9D9',
      'selectColor': 'transparent',
      'highlightColor': 'transparent',
    },
    'default.error.big': {
      'size': 36,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'pink-primary',
      'backgroundColor': '#FFC9D9',
      'selectColor': 'transparent',
      'highlightColor': 'transparent',
    },
    'default.small': {
      'size': 24,
      'highlightSize': 40,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'gray-primary',
      'backgroundColor': 'gray-light',
      'selectColor': 'transparent',
      'highlightColor': 'transparent',
    },
    'default.big': {
      'size': 36,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'gray-primary',
      'backgroundColor': 'gray-light',
      'selectColor': 'transparent',
      'highlightColor': 'transparent',
    },
    'default.error.checked': {
      'size': 30,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'pink-primary',
      'backgroundColor': 'pink-primary',
      'selectColor': '#FFFFFF',
      'highlightColor': 'transparent',
    },
    'default.error.checked.disabled': {
      'size': 30,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'transparent',
      'backgroundColor': 'gray-primary',
      'selectColor': '#FFFFFF',
      'highlightColor': 'transparent',
    },
    'default.error.checked.active': {
      'size': 30,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'pink-primary',
      'backgroundColor': 'pink-primary',
      'selectColor': '#FFFFFF',
      'highlightColor': 'gray-light',
    },
    'default.error.checked.disabled.active': {
      'size': 30,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'pink-primary',
      'backgroundColor': 'gray-primary',
      'selectColor': '#FFFFFF',
      'highlightColor': 'gray-light',
    },
    'default.error.disabled': {
      'size': 30,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'gray-light',
      'backgroundColor': '#F1F5F5',
      'selectColor': 'transparent',
      'highlightColor': 'transparent',
    },
    'default.error.disabled.active': {
      'size': 30,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'pink-primary',
      'backgroundColor': '#F1F5F5',
      'selectColor': 'transparent',
      'highlightColor': 'gray-light',
    },
    'default.error.active': {
      'size': 30,
      'highlightSize': 50,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'pink-primary',
      'backgroundColor': '#FFC9D9',
      'selectColor': 'transparent',
      'highlightColor': 'gray-light',
    },
    'default.error.small.checked': {
      'size': 24,
      'highlightSize': 40,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'pink-primary',
      'backgroundColor': 'pink-primary',
      'selectColor': '#FFFFFF',
      'highlightColor': 'transparent',
    },
    'default.error.small.checked.disabled': {
      'size': 24,
      'highlightSize': 40,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'transparent',
      'backgroundColor': 'gray-primary',
      'selectColor': '#FFFFFF',
      'highlightColor': 'transparent',
    },
    'default.error.small.checked.active': {
      'size': 24,
      'highlightSize': 40,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'pink-primary',
      'backgroundColor': 'pink-primary',
      'selectColor': '#FFFFFF',
      'highlightColor': 'gray-light',
    },
    'default.error.small.checked.disabled.active': {
      'size': 24,
      'highlightSize': 40,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'pink-primary',
      'backgroundColor': 'gray-primary',
      'selectColor': '#FFFFFF',
      'highlightColor': 'gray-light',
    },
    'default.error.small.disabled': {
      'size': 24,
      'highlightSize': 40,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'gray-light',
      'backgroundColor': '#F1F5F5',
      'selectColor': 'transparent',
      'highlightColor': 'transparent',
    },
    'default.error.small.disabled.active': {
      'size': 24,
      'highlightSize': 40,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'pink-primary',
      'backgroundColor': '#F1F5F5',
      'selectColor': 'transparent',
      'highlightColor': 'gray-light',
    },
    'default.error.small.active': {
      'size': 24,
      'highlightSize': 40,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'pink-primary',
      'backgroundColor': '#FFC9D9',
      'selectColor': 'transparent',
      'highlightColor': 'gray-light',
    },
    'default.error.big.checked': {
      'size': 36,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'pink-primary',
      'backgroundColor': 'pink-primary',
      'selectColor': '#FFFFFF',
      'highlightColor': 'transparent',
    },
    'default.error.big.checked.disabled': {
      'size': 36,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'transparent',
      'backgroundColor': 'gray-primary',
      'selectColor': '#FFFFFF',
      'highlightColor': 'transparent',
    },
    'default.error.big.checked.active': {
      'size': 36,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'pink-primary',
      'backgroundColor': 'pink-primary',
      'selectColor': '#FFFFFF',
      'highlightColor': 'gray-light',
    },
    'default.error.big.checked.disabled.active': {
      'size': 36,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'pink-primary',
      'backgroundColor': 'gray-primary',
      'selectColor': '#FFFFFF',
      'highlightColor': 'gray-light',
    },
    'default.error.big.disabled': {
      'size': 36,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'gray-light',
      'backgroundColor': '#F1F5F5',
      'selectColor': 'transparent',
      'highlightColor': 'transparent',
    },
    'default.error.big.disabled.active': {
      'size': 36,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'pink-primary',
      'backgroundColor': '#F1F5F5',
      'selectColor': 'transparent',
      'highlightColor': 'gray-light',
    },
    'default.error.big.active': {
      'size': 36,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'pink-primary',
      'backgroundColor': '#FFC9D9',
      'selectColor': 'transparent',
      'highlightColor': 'gray-light',
    },
    'default.small.checked': {
      'size': 24,
      'highlightSize': 40,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'transparent',
      'backgroundColor': 'blue-primary',
      'selectColor': '#FFFFFF',
      'highlightColor': 'transparent',
    },
    'default.small.checked.disabled': {
      'size': 24,
      'highlightSize': 40,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'transparent',
      'backgroundColor': 'gray-primary',
      'selectColor': '#FFFFFF',
      'highlightColor': 'transparent',
    },
    'default.small.checked.active': {
      'size': 24,
      'highlightSize': 40,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'blue-dark',
      'backgroundColor': 'blue-primary',
      'selectColor': '#FFFFFF',
      'highlightColor': 'gray-light',
    },
    'default.small.checked.disabled.active': {
      'size': 24,
      'highlightSize': 40,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'blue-dark',
      'backgroundColor': 'gray-primary',
      'selectColor': '#FFFFFF',
      'highlightColor': 'gray-light',
    },
    'default.small.disabled': {
      'size': 24,
      'highlightSize': 40,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'gray-light',
      'backgroundColor': '#F1F5F5',
      'selectColor': 'transparent',
      'highlightColor': 'transparent',
    },
    'default.small.disabled.active': {
      'size': 24,
      'highlightSize': 40,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'gray-dark',
      'backgroundColor': '#F1F5F5',
      'selectColor': 'transparent',
      'highlightColor': 'gray-light',
    },
    'default.small.active': {
      'size': 24,
      'highlightSize': 40,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'gray-dark',
      'backgroundColor': 'gray-light',
      'selectColor': 'transparent',
      'highlightColor': 'gray-light',
    },
    'default.big.checked': {
      'size': 36,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'transparent',
      'backgroundColor': 'blue-primary',
      'selectColor': '#FFFFFF',
      'highlightColor': 'transparent',
    },
    'default.big.checked.disabled': {
      'size': 36,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'transparent',
      'backgroundColor': 'gray-primary',
      'selectColor': '#FFFFFF',
      'highlightColor': 'transparent',
    },
    'default.big.checked.active': {
      'size': 36,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'blue-dark',
      'backgroundColor': 'blue-primary',
      'selectColor': '#FFFFFF',
      'highlightColor': 'gray-light',
    },
    'default.big.checked.disabled.active': {
      'size': 36,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'blue-dark',
      'backgroundColor': 'gray-primary',
      'selectColor': '#FFFFFF',
      'highlightColor': 'gray-light',
    },
    'default.big.disabled': {
      'size': 36,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'gray-light',
      'backgroundColor': '#F1F5F5',
      'selectColor': 'transparent',
      'highlightColor': 'transparent',
    },
    'default.big.disabled.active': {
      'size': 36,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'gray-dark',
      'backgroundColor': '#F1F5F5',
      'selectColor': 'transparent',
      'highlightColor': 'gray-light',
    },
    'default.big.active': {
      'size': 36,
      'highlightSize': 60,
      'borderWidth': 2,
      'borderRadius': 4,
      'highlightBorderRadius': 8,
      'borderColor': 'gray-dark',
      'backgroundColor': 'gray-light',
      'selectColor': 'transparent',
      'highlightColor': 'gray-light',
    },
  },
  'Toggle': {
    'meta': {
      'variants': {
        'status': [
          'error',
        ],
        'size': [
          'small',
          'big',
        ],
      },
      'states': [
        'checked',
        'disabled',
        'active',
      ],
    },
    'default': {
      'borderWidth': 1.5,
      'height': 32,
      'width': 52,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'blue-primary',
      'highlightWidth': 62,
      'highlightHeight': 42,
      'highlightColor': 'transparent',
    },
    'default.checked': {
      'borderWidth': 1.5,
      'height': 32,
      'width': 52,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'blue-primary',
      'highlightWidth': 62,
      'highlightHeight': 42,
      'highlightColor': 'transparent',
    },
    'default.checked.disabled': {
      'borderWidth': 1.5,
      'height': 32,
      'width': 52,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'gray-dark',
      'highlightWidth': 62,
      'highlightHeight': 42,
      'highlightColor': 'transparent',
    },
    'default.checked.active': {
      'borderWidth': 1.5,
      'height': 32,
      'width': 52,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'blue-primary',
      'highlightWidth': 62,
      'highlightHeight': 42,
      'highlightColor': '#e5e7ea',
    },
    'default.checked.disabled.active': {
      'borderWidth': 1.5,
      'height': 32,
      'width': 52,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'gray-dark',
      'highlightWidth': 62,
      'highlightHeight': 42,
      'highlightColor': '#e5e7ea',
    },
    'default.disabled': {
      'borderWidth': 1.5,
      'height': 32,
      'width': 52,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'gray-dark',
      'highlightWidth': 62,
      'highlightHeight': 42,
      'highlightColor': 'transparent',
    },
    'default.disabled.active': {
      'borderWidth': 1.5,
      'height': 32,
      'width': 52,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'gray-dark',
      'highlightWidth': 62,
      'highlightHeight': 42,
      'highlightColor': '#e5e7ea',
    },
    'default.active': {
      'borderWidth': 1.5,
      'height': 32,
      'width': 52,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'blue-primary',
      'highlightWidth': 62,
      'highlightHeight': 42,
      'highlightColor': '#e5e7ea',
    },
    'default.error': {
      'borderWidth': 1.5,
      'height': 32,
      'width': 52,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': '#FFD6D9',
      'onTintColor': 'pink-primary',
      'highlightWidth': 62,
      'highlightHeight': 42,
      'highlightColor': 'transparent',
    },
    'default.error.small': {
      'borderWidth': 0.5,
      'height': 22,
      'width': 38,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': '#FFD6D9',
      'onTintColor': 'pink-primary',
      'highlightWidth': 48,
      'highlightHeight': 32,
      'highlightColor': 'transparent',
    },
    'default.error.big': {
      'borderWidth': 2,
      'height': 42,
      'width': 72,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': '#FFD6D9',
      'onTintColor': 'pink-primary',
      'highlightWidth': 82,
      'highlightHeight': 52,
      'highlightColor': 'transparent',
    },
    'default.small': {
      'borderWidth': 0.5,
      'height': 22,
      'width': 38,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'blue-primary',
      'highlightWidth': 48,
      'highlightHeight': 32,
      'highlightColor': 'transparent',
    },
    'default.big': {
      'borderWidth': 2,
      'height': 42,
      'width': 72,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'blue-primary',
      'highlightWidth': 82,
      'highlightHeight': 52,
      'highlightColor': 'transparent',
    },
    'default.error.checked': {
      'borderWidth': 1.5,
      'height': 32,
      'width': 52,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': '#FFD6D9',
      'onTintColor': 'pink-primary',
      'highlightWidth': 62,
      'highlightHeight': 42,
      'highlightColor': 'transparent',
    },
    'default.error.checked.disabled': {
      'borderWidth': 1.5,
      'height': 32,
      'width': 52,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'gray-dark',
      'highlightWidth': 62,
      'highlightHeight': 42,
      'highlightColor': 'transparent',
    },
    'default.error.checked.active': {
      'borderWidth': 1.5,
      'height': 32,
      'width': 52,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': '#FFD6D9',
      'onTintColor': 'pink-primary',
      'highlightWidth': 62,
      'highlightHeight': 42,
      'highlightColor': '#e5e7ea',
    },
    'default.error.checked.disabled.active': {
      'borderWidth': 1.5,
      'height': 32,
      'width': 52,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'gray-dark',
      'highlightWidth': 62,
      'highlightHeight': 42,
      'highlightColor': '#e5e7ea',
    },
    'default.error.disabled': {
      'borderWidth': 1.5,
      'height': 32,
      'width': 52,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'gray-dark',
      'highlightWidth': 62,
      'highlightHeight': 42,
      'highlightColor': 'transparent',
    },
    'default.error.disabled.active': {
      'borderWidth': 1.5,
      'height': 32,
      'width': 52,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'gray-dark',
      'highlightWidth': 62,
      'highlightHeight': 42,
      'highlightColor': '#e5e7ea',
    },
    'default.error.active': {
      'borderWidth': 1.5,
      'height': 32,
      'width': 52,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': '#FFD6D9',
      'onTintColor': 'pink-primary',
      'highlightWidth': 62,
      'highlightHeight': 42,
      'highlightColor': '#e5e7ea',
    },
    'default.error.small.checked': {
      'borderWidth': 0.5,
      'height': 22,
      'width': 38,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': '#FFD6D9',
      'onTintColor': 'pink-primary',
      'highlightWidth': 48,
      'highlightHeight': 32,
      'highlightColor': 'transparent',
    },
    'default.error.small.checked.disabled': {
      'borderWidth': 0.5,
      'height': 22,
      'width': 38,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'gray-dark',
      'highlightWidth': 48,
      'highlightHeight': 32,
      'highlightColor': 'transparent',
    },
    'default.error.small.checked.active': {
      'borderWidth': 0.5,
      'height': 22,
      'width': 38,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': '#FFD6D9',
      'onTintColor': 'pink-primary',
      'highlightWidth': 48,
      'highlightHeight': 32,
      'highlightColor': '#e5e7ea',
    },
    'default.error.small.checked.disabled.active': {
      'borderWidth': 0.5,
      'height': 22,
      'width': 38,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'gray-dark',
      'highlightWidth': 48,
      'highlightHeight': 32,
      'highlightColor': '#e5e7ea',
    },
    'default.error.small.disabled': {
      'borderWidth': 0.5,
      'height': 22,
      'width': 38,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'gray-dark',
      'highlightWidth': 48,
      'highlightHeight': 32,
      'highlightColor': 'transparent',
    },
    'default.error.small.disabled.active': {
      'borderWidth': 0.5,
      'height': 22,
      'width': 38,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'gray-dark',
      'highlightWidth': 48,
      'highlightHeight': 32,
      'highlightColor': '#e5e7ea',
    },
    'default.error.small.active': {
      'borderWidth': 0.5,
      'height': 22,
      'width': 38,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': '#FFD6D9',
      'onTintColor': 'pink-primary',
      'highlightWidth': 48,
      'highlightHeight': 32,
      'highlightColor': '#e5e7ea',
    },
    'default.error.big.checked': {
      'borderWidth': 2,
      'height': 42,
      'width': 72,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': '#FFD6D9',
      'onTintColor': 'pink-primary',
      'highlightWidth': 82,
      'highlightHeight': 52,
      'highlightColor': 'transparent',
    },
    'default.error.big.checked.disabled': {
      'borderWidth': 2,
      'height': 42,
      'width': 72,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'gray-dark',
      'highlightWidth': 82,
      'highlightHeight': 52,
      'highlightColor': 'transparent',
    },
    'default.error.big.checked.active': {
      'borderWidth': 2,
      'height': 42,
      'width': 72,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': '#FFD6D9',
      'onTintColor': 'pink-primary',
      'highlightWidth': 82,
      'highlightHeight': 52,
      'highlightColor': '#e5e7ea',
    },
    'default.error.big.checked.disabled.active': {
      'borderWidth': 2,
      'height': 42,
      'width': 72,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'gray-dark',
      'highlightWidth': 82,
      'highlightHeight': 52,
      'highlightColor': '#e5e7ea',
    },
    'default.error.big.disabled': {
      'borderWidth': 2,
      'height': 42,
      'width': 72,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'gray-dark',
      'highlightWidth': 82,
      'highlightHeight': 52,
      'highlightColor': 'transparent',
    },
    'default.error.big.disabled.active': {
      'borderWidth': 2,
      'height': 42,
      'width': 72,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'gray-dark',
      'highlightWidth': 82,
      'highlightHeight': 52,
      'highlightColor': '#e5e7ea',
    },
    'default.error.big.active': {
      'borderWidth': 2,
      'height': 42,
      'width': 72,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': '#FFD6D9',
      'onTintColor': 'pink-primary',
      'highlightWidth': 82,
      'highlightHeight': 52,
      'highlightColor': '#e5e7ea',
    },
    'default.small.checked': {
      'borderWidth': 0.5,
      'height': 22,
      'width': 38,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'blue-primary',
      'highlightWidth': 48,
      'highlightHeight': 32,
      'highlightColor': 'transparent',
    },
    'default.small.checked.disabled': {
      'borderWidth': 0.5,
      'height': 22,
      'width': 38,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'gray-dark',
      'highlightWidth': 48,
      'highlightHeight': 32,
      'highlightColor': 'transparent',
    },
    'default.small.checked.active': {
      'borderWidth': 0.5,
      'height': 22,
      'width': 38,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'blue-primary',
      'highlightWidth': 48,
      'highlightHeight': 32,
      'highlightColor': '#e5e7ea',
    },
    'default.small.checked.disabled.active': {
      'borderWidth': 0.5,
      'height': 22,
      'width': 38,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'gray-dark',
      'highlightWidth': 48,
      'highlightHeight': 32,
      'highlightColor': '#e5e7ea',
    },
    'default.small.disabled': {
      'borderWidth': 0.5,
      'height': 22,
      'width': 38,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'gray-dark',
      'highlightWidth': 48,
      'highlightHeight': 32,
      'highlightColor': 'transparent',
    },
    'default.small.disabled.active': {
      'borderWidth': 0.5,
      'height': 22,
      'width': 38,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'gray-dark',
      'highlightWidth': 48,
      'highlightHeight': 32,
      'highlightColor': '#e5e7ea',
    },
    'default.small.active': {
      'borderWidth': 0.5,
      'height': 22,
      'width': 38,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'blue-primary',
      'highlightWidth': 48,
      'highlightHeight': 32,
      'highlightColor': '#e5e7ea',
    },
    'default.big.checked': {
      'borderWidth': 2,
      'height': 42,
      'width': 72,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'blue-primary',
      'highlightWidth': 82,
      'highlightHeight': 52,
      'highlightColor': 'transparent',
    },
    'default.big.checked.disabled': {
      'borderWidth': 2,
      'height': 42,
      'width': 72,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'gray-dark',
      'highlightWidth': 82,
      'highlightHeight': 52,
      'highlightColor': 'transparent',
    },
    'default.big.checked.active': {
      'borderWidth': 2,
      'height': 42,
      'width': 72,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'blue-primary',
      'highlightWidth': 82,
      'highlightHeight': 52,
      'highlightColor': '#e5e7ea',
    },
    'default.big.checked.disabled.active': {
      'borderWidth': 2,
      'height': 42,
      'width': 72,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'gray-dark',
      'highlightWidth': 82,
      'highlightHeight': 52,
      'highlightColor': '#e5e7ea',
    },
    'default.big.disabled': {
      'borderWidth': 2,
      'height': 42,
      'width': 72,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'gray-dark',
      'highlightWidth': 82,
      'highlightHeight': 52,
      'highlightColor': 'transparent',
    },
    'default.big.disabled.active': {
      'borderWidth': 2,
      'height': 42,
      'width': 72,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'gray-dark',
      'highlightWidth': 82,
      'highlightHeight': 52,
      'highlightColor': '#e5e7ea',
    },
    'default.big.active': {
      'borderWidth': 2,
      'height': 42,
      'width': 72,
      'offsetValue': 20,
      'thumbColor': '#ffffff',
      'tintColor': 'gray-light',
      'onTintColor': 'blue-primary',
      'highlightWidth': 82,
      'highlightHeight': 52,
      'highlightColor': '#e5e7ea',
    },
  },
  'Layout': {
    'meta': {
      'variants': {},
      'states': [],
    },
    'default': {
      'paddingHorizontal': 16,
      'paddingVertical': 8,
      'backgroundColor': 'transparent',
      'borderColor': 'blue-primary',
      'borderRadius': 3,
      'borderWidth': 1,
    },
  },
};
export const mapping = {
  'Radio': {
    'meta': {
      'variants': {
        'status': [
          'error',
        ],
        'size': [
          'small',
          'big',
        ],
      },
      'states': [
        'checked',
        'disabled',
        'active',
      ],
    },
    'appearance': {
      'default': {
        'mapping': {
          'size': 36,
          'innerSize': 24,
          'highlightSize': 60,
          'borderWidth': 2,
          'borderColor': 'gray-primary',
          'selectColor': 'transparent',
          'highlightColor': 'transparent',
          'state': {
            'active': {
              'borderColor': 'gray-dark',
              'highlightColor': 'gray-light',
            },
            'checked': {
              'borderColor': 'blue-primary',
              'selectColor': 'blue-primary',
            },
            'disabled': {
              'borderColor': 'gray-light',
            },
            'checked.active': {
              'borderColor': 'blue-dark',
            },
            'checked.disabled': {
              'selectColor': 'gray-primary',
            },
          },
        },
        'variant': {
          'status': {
            'error': {
              'mapping': {
                'borderColor': 'pink-primary',
                'state': {
                  'checked': {
                    'borderColor': 'pink-primary',
                    'selectColor': 'pink-primary',
                  },
                  'checked.active': {
                    'borderColor': 'pink-primary',
                  },
                },
              },
            },
          },
          'size': {
            'big': {
              'mapping': {
                'size': 42,
                'innerSize': 28,
                'highlightSize': 70,
              },
            },
            'small': {
              'mapping': {
                'size': 30,
                'innerSize': 20,
                'highlightSize': 50,
              },
            },
          },
        },
      },
    },
  },
  'RadioGroup': {
    'meta': {
      'variants': {},
      'states': [],
    },
    'appearance': {
      'default': {
        'mapping': {
          'padding': 0,
        },
      },
    },
  },
  'CheckBox': {
    'meta': {
      'variants': {
        'status': [
          'error',
        ],
        'size': [
          'small',
          'big',
        ],
      },
      'states': [
        'checked',
        'disabled',
        'active',
      ],
    },
    'appearance': {
      'default': {
        'mapping': {
          'size': 30,
          'highlightSize': 50,
          'borderWidth': 2,
          'borderRadius': 4,
          'highlightBorderRadius': 8,
          'borderColor': 'gray-primary',
          'backgroundColor': 'gray-light',
          'selectColor': 'transparent',
          'highlightColor': 'transparent',
          'state': {
            'active': {
              'borderColor': 'gray-dark',
              'highlightColor': 'gray-light',
            },
            'checked': {
              'borderColor': 'transparent',
              'selectColor': '#FFFFFF',
              'backgroundColor': 'blue-primary',
            },
            'disabled': {
              'borderColor': 'gray-light',
              'backgroundColor': '#F1F5F5',
            },
            'checked.active': {
              'borderColor': 'blue-dark',
            },
            'checked.disabled': {
              'borderColor': 'transparent',
              'backgroundColor': 'gray-primary',
            },
          },
        },
        'variant': {
          'status': {
            'error': {
              'mapping': {
                'borderColor': 'pink-primary',
                'backgroundColor': '#FFC9D9',
                'state': {
                  'active': {
                    'borderColor': 'pink-primary',
                  },
                  'checked': {
                    'borderColor': 'pink-primary',
                    'backgroundColor': 'pink-primary',
                  },
                  'checked.active': {
                    'borderColor': 'pink-primary',
                  },
                },
              },
            },
          },
          'size': {
            'big': {
              'mapping': {
                'size': 36,
                'highlightSize': 60,
              },
            },
            'small': {
              'mapping': {
                'size': 24,
                'highlightSize': 40,
              },
            },
          },
        },
      },
    },
  },
  'Toggle': {
    'meta': {
      'variants': {
        'status': [
          'error',
        ],
        'size': [
          'small',
          'big',
        ],
      },
      'states': [
        'checked',
        'disabled',
        'active',
      ],
    },
    'appearance': {
      'default': {
        'mapping': {
          'borderWidth': 1.5,
          'height': 32,
          'width': 52,
          'offsetValue': 20,
          'thumbColor': '#ffffff',
          'tintColor': 'gray-light',
          'onTintColor': 'blue-primary',
          'highlightWidth': 62,
          'highlightHeight': 42,
          'highlightColor': 'transparent',
          'state': {
            'active': {
              'highlightColor': '#e5e7ea',
            },
            'disabled': {
              'onTintColor': 'gray-dark',
            },
          },
        },
        'variant': {
          'status': {
            'error': {
              'mapping': {
                'tintColor': '#FFD6D9',
                'onTintColor': 'pink-primary',
                'state': {
                  'disabled': {
                    'tintColor': 'gray-light',
                  },
                },
              },
            },
          },
          'size': {
            'big': {
              'mapping': {
                'borderWidth': 2,
                'height': 42,
                'width': 72,
                'highlightWidth': 82,
                'highlightHeight': 52,
              },
            },
            'small': {
              'mapping': {
                'borderWidth': 0.5,
                'height': 22,
                'width': 38,
                'highlightWidth': 48,
                'highlightHeight': 32,
              },
            },
          },
        },
      },
    },
  },
  'Layout': {
    'meta': {
      'variants': {},
      'states': [],
    },
    'appearance': {
      'default': {
        'mapping': {
          'paddingHorizontal': 16,
          'paddingVertical': 8,
          'backgroundColor': 'transparent',
          'borderColor': 'blue-primary',
          'borderRadius': 3,
          'borderWidth': 1,
          'state': {},
        },
      },
    },
  },
};
